base_url: &base_url https://develop.agona.technokratos.com
ui_auth:
  base_url: *base_url
  urn: login/
ui_courses_teacher:
  base_url: *base_url
  urn: courses/teacher
ui_courses_student:
  base_url: *base_url
  urn: courses/student
ui_auth_admin_username: admin_agona@technokratos.com
ui_auth_teacher_username: admin_agona@technokratos.com
ui_auth_student_username: test_user@mail.ru
api_url: 
login_url: https://develop.agona.technokratos.com/login
db_host: 
db_port: 
db_name: 
db_user: 
# ui_auth_password: provide your password using command line