base_url: &base_url https://acare-test.exactsciences.net/acare
env: test
ui_auth:
  base_url: *base_url
  urn: reports/#/login
base_url:
  base_url: *base_url
  urn: qcmetrics/
ui_reports_engine: 
  base_url: *base_url
  urn: reports/#/dashboard
ui_rules_engine:
  base_url: *base_url
  urn: rules/#/app/dashboard
ui_auth_username: admin_agona@technokratos.com
ui_username: RUSLAN IMANKULOV
api_url: https://acare-test.exactsciences.net/qcmetrics/api/v1
login_url: https://acare-test.exactsciences.net/acare/api/v1/login
db_host: qcmetrics-test.co7dhejttgpm.us-west-2.rds.amazonaws.com
db_port: 5432
db_name: postgres
db_user: qua_lpitelina
# ui_auth_password: provide your password using command line