name: Docker Image CI

on: [workflow_dispatch]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: PrepareReg Names
      run: |
        echo IMAGE_REPOSITORY=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]') >> $GITHUB_ENV
        echo IMAGE_TAG=$(echo ${{ github.ref }} | tr '[:upper:]' '[:lower:]' | awk '{split($0,a,"/"); print a[3]}') >> $GITHUB_ENV

    - name: Build Docker image
      run: |
        docker build . --tag ghcr.io/${{ env.IMAGE_REPOSITORY}}/${{ env.IMAGE_TAG }}
        docker run ghcr.io/${{ env.IMAGE_REPOSITORY}}/${{ env.IMAGE_TAG }}
        docker push ghcr.io/${{ env.IMAGE_REPOSITORY}}/${{ env.IMAGE_TAG }}
