# This is a basic workflow that is manually triggered

name: UI_TESTS

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on: [workflow_dispatch]
jobs:
  test:
    runs-on: ubuntu-latest
    container: ghcr.io/imankulov-ruslan/my-svc
    steps:
    - name: test  
      run: |
        cd /app
        echo ${{ secrets.NAME }}
        robot --variable ui_auth_password:${{ secrets.UI_AUTH_PASSWORD }} -A src/config/test-runner/dev-args.robot
        git config user.email ${{ secrets.EMAIL }}
        git config user.name ${{ secrets.NAME }}
        git remote add tests https://Imankulov-ruslan:${{ secrets.PASSWORD }}@github.com/Imankulov-ruslan/IP_auto_tests.git
        git checkout -b test-results
        git add -A .
        git status
        git commit -m "deploy"
        git push -f https://Imankulov-ruslan:${{ secrets.PASSWORD }}@github.com/Imankulov-ruslan/IP_auto_tests.git

