# This is a basic workflow that is manually triggered

name: UI_TESTS

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on: [workflow_dispatch]
jobs:
  test:
    runs-on: ubuntu-latest
    container: 
     image: ghcr.io/imankulov-ruslan/my-svc
     options: --name test
    steps:
    - name: test  
      run: |
        cd /app
        robot --variable ui_auth_password:${{ secrets.UI_AUTH_PASSWORD }} -A src/config/test-runner/dev-args.robot
        exit
        cd /app
        ls -a


