# This is a basic workflow that is manually triggered

name: UI_TESTS

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on: [workflow_dispatch]
jobs:
  test:
    runs-on: ubuntu-latest
    container: ghcr.io/imankulov-ruslan/my-svc
    steps:
    - name: test  
      run:
        cd /app;
        robot --variable ui_auth_password:${{secrets.UI_AUTH_PASSWORD}} -A src/config/test-runner/dev-args.robot;
    - name: Archive code coverage results
      uses: actions/upload-artifact@v3
      with:
        name: test-report
        path: ./reports/report.html
    - name: Copy from container to host
      uses: tj-actions/docker-cp@v2
      with:
        container: ghcr.io/imankulov-ruslan/my-svc
        source: /reports/report.html
        destination: ./reports/report.html
