# This is a basic workflow that is manually triggered

name: UI_TESTS

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on: [workflow_dispatch]
jobs:
  test:
    runs-on: ubuntu-latest
    container: 
     image: ghcr.io/imankulov-ruslan/my-svc
     options: --name test
    steps:
    - name: test  
      run: |
        cd /app
        robot --variable ui_auth_password:${{ secrets.UI_AUTH_PASSWORD }} -A src/config/test-runner/dev-args.robot
    - name: Archive code coverage results
      uses: actions/upload-artifact@v3
      with:
        name: test-report
        path: /app/reports/report.html
  deploy:
    if: ${{ always() }}
    needs: [test]
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
     contents: read
     pages: write
     id-token: write
    runs-on: ubuntu-latest
    steps:
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - uses: actions/download-artifact@v3
        with:
          name: test-report
          path: '.'
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
         path: '.'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
      


